stages:
  - docker-build

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: "amsitc/ams-dashboard"
    IMAGE_TAG: "$CI_COMMIT_TAG"
  script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - echo "username $DOCKERHUB_PASSWORD"
    - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_NAME:$IMAGE_TAG"
  only:
    - tags